project:
  type: website

website:
  title: "陈加铿的个人博客"
  bread-crumbs: true
  back-to-top-navigation: true
  page-footer: "© Yuan Li 2024"
  reader-mode: true
  repo-url: https://github.com/CHEN-jiakeng/demo
  repo-actions: [edit, issue]

  navbar:
    background: primary
    foreground: light
    pinned: true
    search: true
    left:
     # - text: "主页"
        #file: home.qmd
      - text: "计量基础"
        file: index.qmd
     # - text: "Stata"
        #file: references.qmd
      - text: "个人简历"
        file: about.qmd
    right:
      - icon: github
        menu:
        - text: Source Code
          url: https://code.com
        - text: Report a Bug
          url: https://bugs.com
      - icon: twitter
        href: https://twitter.com
      - icon: google
        href: http://google.com/

  sidebar:
    - title: "博客"
      style: docked
      type: dark
      background: light
      contents:
        - index.qmd
        - techs.qmd
        - papers.qmd
        - books.qmd

    - title: "资料"
      contents:
        - references.qmd
        # navigation items